/**
 * Task CRUD Error Types
 * 
 * Centralized error definitions for task operations
 */

export const TASK_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CREATE_ERROR: 'CREATE_ERROR',
  GET_ERROR: 'GET_ERROR',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',
  UPDATE_ERROR: 'UPDATE_ERROR',
  DELETE_ERROR: 'DELETE_ERROR',
  HARD_DELETE_ERROR: 'HARD_DELETE_ERROR',
  RESTORE_ERROR: 'RESTORE_ERROR',
  INVALID_ID: 'INVALID_ID',
  INVALID_UPDATES: 'INVALID_UPDATES',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_DELETED: 'TASK_DELETED',
  DUPLICATE_TASK: 'DUPLICATE_TASK'
};

